source 'https://rubygems.org'
gem 'jekyll', github: 'jekyll/jekyll'

group :jekyll_plugins do
	gem 'jekyll-commonmark', github: 'jekyll/jekyll-commonmark'
	gem 'jekyll-feed'
	gem 'jekyll-seo-tag'
	gem 'jekyll-sitemap'
	gem 'jekyll-last-modified-at'
	gem 'jekyll-target-blank'
	gem 'jekyll-watch'
	gem 'jekyll-redirect-from'
	gem 'jekyll-email-protect'
#	gem 'jekyll-datapage-generator'
	gem 'jekyll-debug'
	gem 'jekyll-mentions'
#	gem 'jekyll-liquify'
	gem 'jekyll-auto-image'
	gem 'html-proofer'
#	gem 'jekyll-toc'
#	gem 'jekyll-lunr'
	gem 'liquid-c'
	gem 'jekyll-webmention_io', github: 'aarongustafson/jekyll-webmention_io'
#	gem 'jekyll-admin'
#	gem 'jekyll-optional-front-matter'
#	gem 'jekyll-paginate'
	gem 'jekyll-paginate-v2'
#	gem 'jekyll-archives'
#	gem 'jekyll-youtube'
#	gem 'jekyll-spaceship'
#	gem 'jekyll-pdf-embed'
#	gem 'jekyll-giphy'
#	gem 'jekyll-timeago'
#	gem 'liquid_pluralize'
#	gem 'liquid_reading_time'
#	gem 'jekyll-twitter-plugin'
#	gem 'jekyll-news-sitemap'
#	gem 'jekyll-git_metadata'
#	gem 'jekyll-auto-image'
#	gem 'jekyll-tagging'
#	gem 'jekyll-auto-image'
#	gem 'premonition'
#	gem 'jekyll-stork'
	gem 'jekyll-wikilinks'
#	gem 'jekyll-favicon' # my favicons are not uniform
	gem 'jekyll-graph'
	gem 'jekyll-minifier', github: 'digitalsparky/jekyll-minifier'
end
